<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="images/logo.png" rel="icon" />
        <NoAutoGeneratedIdViewHandlertitle>JSP Page</title>
        <title><%= application.getAttribute("applicationLabel") %></title>
        <link href="./css/bootstrap.min.css" rel="stylesheet">
        <link href="./css/style.css" rel="stylesheet">
        <script src="./js/jquery.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row navbar-fixed-top">
                <nav class="navbar navbar-default header">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand logo" href="#">
                                <img alt="Brand" src="images/logo.png">
                            </a>
                            <div class="navbar-text title">
                                <p>Hospital Management System</p>
                            </div>
                        </div>
                    </div>
                </nav>
                <%= request.getServletPath().equals("/register_patient.jsp") ?
                "<a href=\"./login.jsp\" style=\"text-align:Center;font-weight:bold;font-size:110%;padding: 0 2%;color:rgb(253, 250, 250)\">LOGIN</a>" :
                ""%>
            </div>